name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_simple.py
        python test_ransomware_detection.py
    
    - name: Build executable
      run: |
        python create_simple_exe_direct.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: dist/
